FROM rust:1.82-slim-bookworm

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN rustup component add \
    clippy \
    rustfmt \
    rust-analyzer

WORKDIR /workspace

CMD ["sleep", "infinity"]
